// #import "@preview/touying:0.6.1": *
// #import themes.simple: *

// #show: simple-theme.with(
//   aspect-ratio: "16-9",
//   footer: [Simple slides],
// )

// #title-slide[
//   = Keep it simple!
//   #v(2em)

//   Alpha #footnote[Uni Augsburg] #h(1em)
//   Bravo #footnote[Uni Bayreuth] #h(1em)
//   Charlie #footnote[Uni Chemnitz] #h(1em)

//   July 23
// ]

// == First slide

// #lorem(20)

// #focus-slide[
//   _Focus!_

//   This is very important.
// ]

// = Let's start a new section!

// == Dynamic slide

// Did you know that...

// #pause

// ...you can see the current section at the top of the slide?
= Introduction
<introduction>
This document was generated by Logisim-evolution. Any part of the TeX
sources can be used in your own documents without any problems. In case
you want to use all/parts of this generated TeX-sources please \(1) do
not forget to include the required packages, and \(2) include a remark
that this source was generated by Logisim-evolution.

= Truth table
<truth-table>
The table may be way to big to be displayed on the page. At generation
time no calculation was done on the size of the table with respect to
the width/height of the page.

== Compacted truth table
<compacted-truth-table>
#block[
  #figure(
    align(center)[#table(
      columns: 12,
      align: (col, row) => (
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
      ).at(col),
      inset: 6pt,
      [$A$], [$B$], [$C$], [$D$], [$a$], [$b$], [$c$], [$d$], [$e$], [$f$], [$g$], [$h$],
      [$0$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$],
      [$0$], [$0$], [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$0$], [$0$], [$0$], [$0$],
      [$0$], [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$0$],
      [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$1$], [$0$],
      [$0$], [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$0$], [$0$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$0$], [$0$], [$0$],
      [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$],
      [$1$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$1$], [$1$], [$0$],
      [$1$], [$-$], [$1$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$1$], [$0$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
    )],
  )

]
== Complete truth table
<complete-truth-table>
#block[
  #figure(
    align(center)[#table(
      columns: 12,
      align: (col, row) => (
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
        center,
      ).at(col),
      inset: 6pt,
      [$A$], [$B$], [$C$], [$D$], [$a$], [$b$], [$c$], [$d$], [$e$], [$f$], [$g$], [$h$],
      [$0$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$],
      [$0$], [$0$], [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$0$], [$0$], [$0$], [$0$],
      [$0$], [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$0$],
      [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$1$], [$0$],
      [$0$], [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$0$], [$0$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$],
      [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$0$], [$0$], [$0$],
      [$1$], [$0$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$1$], [$0$],
      [$1$], [$0$], [$0$], [$1$], [$1$], [$1$], [$1$], [$0$], [$0$], [$1$], [$1$], [$0$],
      [$1$], [$0$], [$1$], [$0$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$0$], [$1$], [$1$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$1$], [$0$], [$0$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$1$], [$0$], [$1$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$1$], [$1$], [$0$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
      [$1$], [$1$], [$1$], [$1$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$-$], [$1$],
    )],
  )

]
= Karnaugh diagrams
<karnaugh-diagrams>
This section shows various versions of the Karnaugh diagrams of the
given functions.

== Empty Karnaugh diagrams
<empty-karnaugh-diagrams>
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
== Filled in Karnaugh diagrams
<filled-in-karnaugh-diagrams>
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
== Filled in Karnaugh diagrams with covers
<filled-in-karnaugh-diagrams-with-covers>
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
#block[
]
= Minimal expressions
<minimal-expressions>
$a = overline(B) dot.op overline(D) + B dot.op D + A + overline(B) dot.op C$~
\
$b = overline(B) + overline(C) dot.op overline(D) + C dot.op D$~ \
$c = overline(C) + D + B$~ \
$d = overline(B) dot.op overline(D) + overline(B) dot.op C + B dot.op overline(C) dot.op D + C dot.op overline(D)$~
\
$e = overline(B) dot.op overline(D) + C dot.op overline(D)$~ \
$f = overline(C) dot.op overline(D) + B dot.op overline(C) + B dot.op overline(D) + A$~
\
$g = overline(B) dot.op C + B dot.op overline(C) + A + C dot.op overline(D)$~
\
$h = A dot.op C + A dot.op B$~ \
