name: Build PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: hws
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile PDF
        run: |
          typst c calculus/main.typ calculus.pdf --root .

      - name: Update `latest` Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -f latest  # 强制更新最新的 `latest` 标签
          git push origin -f latest  # 强制推送标签到远程

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: calculus.pdf
          make_latest: true
          tag_name: latest  # 指定标签为 `latest`
          name: "pdfs"
          body: ""
