name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 1 * *'
# run monthly

jobs:
  cleanup:
    runs-on: nixos
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2
